package semtd_intranet.semtd_net.enums;

//CARGOS DE USUARIO
public enum Cargo {
    GERENTE_EXECUTIVO,
    GERENTE_OPERACIONAL,
    DIRETOR,
    SECRETARIO_EXECUTIVO,
    ANALISTA_ADMINISTRATIVO,
    TECNICO_ADMINISTRATIVO,
    ASSISTENTE_TECNICO,
    PRESTADOR_DE_SERVICOS,
    ESTAGIARIO,
    ANALISTA,
    OUTROS
}
